name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: martellienrico/stickerify-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
